### ISSUE TITLE
Support for xapk

### ISSUE THREAD

**Issue by NicolasVautrin** [commonuserlol/fgi#4]
hi , do you plan to support the xapk format. I am currently on an archive of this type which contains 2 apks. These 2 apks must have the same signature, patched and not patched one.
C:\VirtualBox_SharedFiles\Tacticus>adb install-multiple patched_base.apk config.armeabi_v7a.apk
adb: failed to finalize session
Failure [INSTALL_FAILED_INVALID_APK: /data/app/vmdl859264819.tmp/config.armeabi_v7a.apk signatures are inconsistent]

**Comment by commonuserlol** [comment]
As workaround you can extract xapk to current working directory (or somewhere else) and use `-i .` as you do for splits. However I'll implement xapk support soon

**Comment by NicolasVautrin** [comment]
C:\VirtualBox_SharedFiles\Tacticus>dir
 Le volume dans le lecteur C n’a pas de nom.
 Le numéro de série du volume est E2FE-5C52

 Répertoire de C:\VirtualBox_SharedFiles\Tacticus

16/08/2024  22:24    <DIR>          .
16/08/2024  22:24    <DIR>          ..
16/08/2024  22:22       136 510 379 com.snowprintstudios.tacticus.apk
16/08/2024  22:22        36 582 954 config.armeabi_v7a.apk
16/08/2024  22:22           414 638 icon.png
16/08/2024  22:22             3 516 manifest.json
               4 fichier(s)      173 511 487 octets
               2 Rép(s)  17 592 872 960 octets libres

C:\VirtualBox_SharedFiles\Tacticus>fgi -i . --config-type listen
1s - I: Merging split APKs...
1s - E: Command ['java', '-jar', WindowsPath('C:/Users/nicolasv/.fgi/apkeditor.jar'), 'm', '-i', WindowsPath('C:/Users/nicolasv/AppData/Local/Temp/Tacticus-mt'), '-o', WindowsPath('C:/Users/nicolasv/AppData/Local/Temp/.m.apk')] returned non-zero exit status: 00.000 I: [MERGE] Using: APKEditor version 1.3.9, ARSCLib version 1.3.5
00.011 I: [MERGE] Merging ...
   Input: C:\Users\nicolasv\AppData\Local\Temp\Tacticus-mt
 Output: C:\Users\nicolasv\AppData\Local\Temp\.m.apk
 ----------------------------
00.011 I: [MERGE] Searching apk files ...

ERROR:
java.io.FileNotFoundException: No '*.apk' files in directory: C:\Users\nicolasv\AppData\Local\Temp\Tacticus-mt
        at com.reandroid.apk.ApkBundle.loadApkDirectory(ApkBundle.java:129)
        at com.reandroid.apkeditor.merge.Merger.run(Merger.java:61)
        at com.reandroid.apkeditor.merge.Merger.execute(Merger.java:235)
        at com.reandroid.apkeditor.Main.execute(Main.java:89)
        at com.reandroid.apkeditor.Main.execute(Main.java:64)
        at com.reandroid.apkeditor.Main.main(Main.java:36)

**Comment by NicolasVautrin** [comment]
C:\VirtualBox_SharedFiles\Tacticus>dir
 Le volume dans le lecteur C n’a pas de nom.
 Le numéro de série du volume est E2FE-5C52

 Répertoire de C:\VirtualBox_SharedFiles\Tacticus

16/08/2024  22:24    <DIR>          .
16/08/2024  22:24    <DIR>          ..
16/08/2024  22:22       136 510 379 base.apk
16/08/2024  22:22        36 582 954 config.armeabi_v7a.apk
16/08/2024  22:22           414 638 icon.png
16/08/2024  22:22             3 516 manifest.json
               4 fichier(s)      173 511 487 octets
               2 Rép(s)  17 592 872 960 octets libres

C:\VirtualBox_SharedFiles\Tacticus>fgi -i . --config-type listen
1s - I: Merging split APKs...
1s - E: Command ['java', '-jar', WindowsPath('C:/Users/nicolasv/.fgi/apkeditor.jar'), 'm', '-i', WindowsPath('C:/Users/nicolasv/AppData/Local/Temp/Tacticus-mt'), '-o', WindowsPath('C:/Users/nicolasv/AppData/Local/Temp/.m.apk')] returned non-zero exit status: 00.000 I: [MERGE] Using: APKEditor version 1.3.9, ARSCLib version 1.3.5
00.011 I: [MERGE] Merging ...
   Input: C:\Users\nicolasv\AppData\Local\Temp\Tacticus-mt
 Output: C:\Users\nicolasv\AppData\Local\Temp\.m.apk
 ----------------------------
00.011 I: [MERGE] Searching apk files ...

ERROR:
java.io.FileNotFoundException: No '*.apk' files in directory: C:\Users\nicolasv\AppData\Local\Temp\Tacticus-mt
        at com.reandroid.apk.ApkBundle.loadApkDirectory(ApkBundle.java:129)
        at com.reandroid.apkeditor.merge.Merger.run(Merger.java:61)
        at com.reandroid.apkeditor.merge.Merger.execute(Merger.java:235)
        at com.reandroid.apkeditor.Main.execute(Main.java:89)
        at com.reandroid.apkeditor.Main.execute(Main.java:64)
        at com.reandroid.apkeditor.Main.main(Main.java:36)

**Comment by commonuserlol** [comment]
Can you run `dir` in directory where you ran fgi

**Comment by NicolasVautrin** [comment]
it's in the trace

**Comment by commonuserlol** [comment]
wdym? I guess you ran fgi in wrong directory

**Comment by NicolasVautrin** [comment]
no first command is dir then i ran fgi

**Comment by commonuserlol** [comment]
Oh right, I guess it not found cuz fgi filters out config assuming its non-target one. I'll add support for xapk soon

**Comment by commonuserlol** [comment]
I've just pushed initial support, however it doesn't support XAPK with .obb (usually you call it "cache") and was blindly coded since I dont have any XAPK for test. Let me know about result

**Comment by NicolasVautrin** [comment]
I think you search smali in the lib Apk ^^

c:\VirtualBox_SharedFiles\Tacticus>dir
 Le volume dans le lecteur C n’a pas de nom.
 Le numéro de série du volume est E2FE-5C52

 Répertoire de c:\VirtualBox_SharedFiles\Tacticus

17/08/2024  17:50    <DIR>          .
17/08/2024  17:50    <DIR>          ..
16/08/2024  22:22       136 510 379 com.snowprintstudios.tacticus.apk
16/08/2024  22:22        36 582 954 config.armeabi_v7a.apk
16/08/2024  22:22           414 638 icon.png
16/08/2024  22:22             3 516 manifest.json
               4 fichier(s)      173 511 487 octets
               2 Rép(s)  18 133 540 864 octets libres

c:\VirtualBox_SharedFiles\Tacticus>fgi -i . --config-type listen
1s - I: Merging split APKs...
1s - I: Decoding APK to C:\Users\nicolasv\AppData\Local\Temp\zWczSbJRBAMU...
2s - I: Looking for .smali...
2s - E: Couldn't find smali containing entrypoint ()

**Comment by NicolasVautrin** [comment]
is there a way to mp you , then i'll share the xapk link i'm work on ?

**Comment by zeroz-code** [comment]
@commonuserlol off topic. I just wanted to ask about
What happened with your frida java menu repo?

**Comment by commonuserlol** [comment]
@zeroz-code It's under rewrite cuz code quality was bad. Gonna publish it tomorrow as new repo
